const IncAction = {
    INCREASE_SYNC: 'INCREASE_SYNC',
    INCREASE_SYNC_SUCCESS: 'INCREASE_SYNC_SUCCESS', 
    INCREASE_SYNC_FAILED: 'INCREASE_SYNC_FAILED', 
    INCREASE_ASYNC: 'INCREASE_ASYNC', 
}

const DecAction = {
    DECREASE_SYNC: 'DECREASE_SYNC',
    DECREASE_SYNC_SUCCESS: 'DECREASE_SYNC_SUCCESS', 
    DECREASE_SYNC_FAILED: 'DECREASE_SYNC_FAILED', 
    DECREASE_ASYNC: 'DECREASE_ASYNC', 
}

export {
    IncAction, DecAction
};